
hola: hola.cpp
	g++ hola.cpp -o hola


# CC = g++
# CFLAGS = -g
# DEPS = imprime.h
# OBJS= imprime.o main.o
# el2: $(OBJS)
# 	$(CC) $^ -o el2 $(CFALGS)
# %.0: %.cpp $(DEPS)
# 	$(CC) -c $<
# Regla generica
# variables internas de make
# $< primera dependencia:
#Regla tontorrona
#.PHONY: clean
# clean:
# 	$(RM) *.o
