DROP DATABASE IF EXISTS Empresa;

CREATE DATABASE Empresa;

USE Empresa;

CREATE TABLE EMPLEADOS(
    DNI DECIMAL(8),
    NOMBRE VARCHAR(10),
    APELLIDO1 VARCHAR(15),
    APELLIDO2 VARCHAR(15),
    DIRECC1 VARCHAR(25),
    DIRECC2 VARCHAR(20),
    CIUDAD VARCHAR(20),
    PROVINCIA VARCHAR(20),
    COD_POSTAL VARCHAR(5),
    SEXO VARCHAR(1),
    FECHA_NAC DATE
);

CREATE TABLE DEPARTAMENTOS (
    DPTO_COD DECIMAL(5),
    NOMBRE_DPTO VARCHAR(30),
    DPTO_PADRE  DECIMAL(5),
    PRESUPUESTO DECIMAL,
    PRES_ACTUAL DECIMAL
);

CREATE TABLE HISTORIAL_LABORAL (
    EMPLEADO_DNI DECIMAL(8),
    TRABAJO_COD DECIMAL(5),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DPTO_COD DECIMAL(5),
    SUPERVISOR_DNI DECIMAL(8)
);

CREATE TABLE UNIVERSIDADES (
    UNIV_COD DECIMAL(5),
    NOMBRE_UNIV VARCHAR(25),
    CIUDAD VARCHAR(20),
    MUNICIPIO VARCHAR(2),
    COD_POSTAL VARCHAR(5)
);

CREATE TABLE HISTORIAL_SALARIAL (
    EMPLEADO_DNI DECIMAL(8),
    SALARIO DECIMAL,
    FECHA_COMIENZO DATE,
    FECHA_FIN DATE
);

CREATE TABLE TRABJAOS (
    TRABAJO_COD DECIMAL (5),
    NOMBRE_TRAB VARCHAR (20),
    SALARIO_MIN DECIMAL (2),
    SALARIO_MAX DECIMAL (2)
);