USE Empresa;

ALTER TABLE EMPLEADOS MODIFY NOMBRE VARCHAR(10) NOT NULL;
ALTER TABLE EMPLEADOS MODIFY APELLIDO1 VARCHAR(15) NOT NULL;
ALTER TABLE DEPARTAMENTOS MODIFY NOMBRE_DPTO VARCHAR(30) NOT NULL;
ALTER TABLE DEPARTAMENTOS MODIFY PRESUPUESTO DECIMAL NOT NULL;
ALTER TABLE UNIVERSIDADES MODIFY NOMBRE_UNIV VARCHAR(25) NOT NULL;
ALTER TABLE HISTORIAL_SALARIAL MODIFY SALARIO DECIMAL NOT NULL;
ALTER TABLE TRABJAOS MODIFY NOMBRE_TRAB VARCHAR (20) NOT NULL;
ALTER TABLE TRABJAOS MODIFY SALARIO_MIN DECIMAL (2) NOT NULL;
ALTER TABLE TRABJAOS MODIFY SALARIO_MAX DECIMAL (2) NOT NULL;

ALTER TABLE EMPLEADOS MODIFY SEXO ENUM ("H", "M");
ALTER TABLE DEPARTAMENTOS ADD UNIQUE (NOMBRE_DPTO);
ALTER TABLE TRABJAOS ADD UNIQUE (NOMBRE_TRAB);


ALTER TABLE EMPLEADOS ADD PRIMARY KEY (DNI);
ALTER TABLE DEPARTAMENTOS ADD PRIMARY KEY (DPTO_COD);
ALTER TABLE HISTORIAL_LABORAL ADD PRIMARY KEY (EMPLEADO_DNI, TRABAJO_COD);
ALTER TABLE UNIVERSIDADES ADD PRIMARY KEY (UNIV_COD);
ALTER TABLE HISTORIAL_SALARIAL ADD PRIMARY KEY (EMPLEADO_DNI);
ALTER TABLE TRABJAOS ADD PRIMARY KEY (TRABAJO_COD);

ALTER TABLE HISTORIAL_LABORAL ADD FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS (DNI);
ALTER TABLE HISTORIAL_LABORAL ADD FOREIGN KEY (SUPERVISOR_DNI) REFERENCES EMPLEADOS (DNI);
ALTER TABLE HISTORIAL_LABORAL ADD FOREIGN KEY (TRABAJO_COD) REFERENCES TRABJAOS (TRABAJO_COD);
ALTER TABLE HISTORIAL_LABORAL ADD FOREIGN KEY (DPTO_COD) REFERENCES DEPARTAMENTOS (DPTO_COD);
ALTER TABLE HISTORIAL_SALARIAL ADD FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS (DNI);